/* =====================================================================
   CEO Loan Intelligence Dashboard - stored procedure
   Designed and architected by CHINTALA MAHINDRA

   Procedure : dbo.USP_CEO_DASH_REPAYMENT_CUBE
   Java      : CeoLoanIntelligenceDAOImpl.getRepaymentCube()
   Replaces  : the inline SQL that CeoLoanIntelligenceDAOImpl.getRepaymentCube() used to run
   Runs      : snapshot build (24 months); the largest repayment read
   Returns   : repayments per district / mandal / credit month / project, with payment modes

   Test in QueryTool / SSMS:
     EXEC dbo.USP_CEO_DASH_REPAYMENT_CUBE @From = '2024-11-01', @To = '2026-11-01', @SnOnly = 1, @PayModes = 1;
   ===================================================================== */

CREATE OR ALTER PROCEDURE dbo.USP_CEO_DASH_REPAYMENT_CUBE
    @From DATETIME,
    @To DATETIME,
    @SnOnly BIT = 1,
    @PayModes BIT = 1
AS
BEGIN
    SET NOCOUNT ON;

    SELECT VI.DISTRICT_ID, VI.MANDAL_ID, CONVERT(CHAR(7), BC.CREDITED_DATE, 120) AS PERIOD_MONTH, MCP.PROJECT_TYPE,
           COUNT(*) AS REPAYMENT_TXN_COUNT,
           SUM(SCI.REPAID_AMOUNT) AS REPAID_AMOUNT,
           SUM(CASE WHEN UPPER(SCI.REPAY_STATUS) = 'CLOSED' THEN SCI.REPAID_AMOUNT ELSE 0 END) AS REPAID_AMOUNT_CLOSED,
           SUM(CASE WHEN SCI.IS_PROCESSED = 'N' THEN SCI.REPAID_AMOUNT ELSE 0 END) AS REPAID_AMOUNT_UNPROCESSED,
           SUM(CASE WHEN LTRIM(RTRIM(ISNULL(SCI.Adjust_Type, ''))) <> '' THEN SCI.REPAID_AMOUNT ELSE 0 END) AS REPAID_AMOUNT_ADJUSTMENT,
           COUNT(DISTINCT SM.MEMBER_ID) AS MEMBERS_ACTIVE_REPAY_SIDE,
           SUM(CASE WHEN @PayModes = 1 AND PM.MODE_CODE = 3 THEN SCI.REPAID_AMOUNT ELSE 0 END) AS REPAID_POS,
           SUM(CASE WHEN @PayModes = 1 AND PM.MODE_CODE = 2 THEN SCI.REPAID_AMOUNT ELSE 0 END) AS REPAID_UPI,
           SUM(CASE WHEN @PayModes = 1 AND PM.MODE_CODE = 1 THEN SCI.REPAID_AMOUNT ELSE 0 END) AS REPAID_AUTO,
           SUM(CASE WHEN @PayModes = 1 AND PM.MODE_CODE = 3 THEN 1 ELSE 0 END) AS TXNS_POS,
           SUM(CASE WHEN @PayModes = 1 AND PM.MODE_CODE = 2 THEN 1 ELSE 0 END) AS TXNS_UPI,
           SUM(CASE WHEN @PayModes = 1 AND PM.MODE_CODE = 1 THEN 1 ELSE 0 END) AS TXNS_AUTO
      FROM SHG_CREDIT_INFO SCI WITH (NOLOCK)
     INNER JOIN (SELECT BCI.BANK_REF_NO, MIN(BCI.CREDITED_DATE) AS CREDITED_DATE
                   FROM BANKS_CREDIT_INFO BCI WITH (NOLOCK)
                  WHERE BCI.CREDITED_DATE >= @From AND BCI.CREDITED_DATE < @To
                    AND BCI.BANK_REF_NO IS NOT NULL
                  GROUP BY BCI.BANK_REF_NO) BC ON BC.BANK_REF_NO = SCI.BANK_REF_NO
     INNER JOIN (SELECT VC.BANK_REF_NO,
                        MAX(CASE WHEN VC.CREATED_BY = 'PAYTM PAYMENT SERVICE'  THEN 3
                                 WHEN VC.CREATED_BY = 'Phi PAYMENT SERVICE'    THEN 2
                                 WHEN VC.CREATED_BY = 'SHG AUTO DEBIT PROCESS' THEN 1 ELSE 0 END) AS MODE_CODE,
                        MAX(VC.CREATED_BY) AS CB
                   FROM VO_CREDIT_INFO VC WITH (NOLOCK)
                  WHERE VC.BANK_REF_NO IS NOT NULL AND VC.VO_REPAY_STATUS = 'CLOSED'
                  GROUP BY VC.BANK_REF_NO) PM ON PM.BANK_REF_NO = SCI.BANK_REF_NO
     INNER JOIN SHG_MEMBER_MCP_INFO MCP WITH (NOLOCK) ON MCP.SHG_MEMBER_LOAN_ACCNO = SCI.SHG_MEMBER_LOAN_ACCNO
     INNER JOIN (SELECT MEMBER_ID, MAX(SHG_ID) AS SHG_ID, MAX(CATAGORY) AS CATEGORY
                   FROM SHG_MEMBER_INFO WITH (NOLOCK)
                  WHERE IS_MEM_ACTIVE = 'Y' AND LEN(LTRIM(RTRIM(MEMBER_ID))) >= 20
                  GROUP BY MEMBER_ID) SM ON SM.MEMBER_ID = MCP.MEMBER_LONG_CODE
     INNER JOIN SHG_INFO SI WITH (NOLOCK) ON SI.TRANS_SHG_ID = SM.SHG_ID AND SI.IS_ACTIVE = 'Y'
     INNER JOIN VO_INFO VI WITH (NOLOCK) ON VI.TRANS_VO_ID = SI.VO_ID AND VI.IS_ACTIVE = 'Y'
     WHERE SCI.SHG_MEMBER_LOAN_ACCNO <> ''
       AND MCP.MEMBER_LONG_CODE IS NOT NULL
       AND LTRIM(RTRIM(MCP.MEMBER_LONG_CODE)) <> ''
       AND LEN(MCP.MEMBER_LONG_CODE) >= 20
       AND MCP.ISSUED_DATE IS NOT NULL
       AND MCP.ISSUED_DATE > '2000-01-01'
       AND MCP.LOAN_STATUS IN ('OPEN', 'CLOSED')
       AND (@SnOnly = 0 OR MCP.PROJECT_TYPE IN (SELECT PROJECT_TYPE FROM PROJECT_TYPE_LOAN_MAPPING WITH (NOLOCK)
                                                WHERE LTRIM(RTRIM(LOAN_TYPE)) = 'SN'))
       AND EXISTS (SELECT 1 FROM DISTRICT_MASTER DM WITH (NOLOCK)
                    WHERE DM.DISTRICT_ID = VI.DISTRICT_ID AND DM.FLAG = 'Y')
       AND EXISTS (SELECT 1 FROM MANDAL_MASTER MM WITH (NOLOCK)
                    WHERE MM.DISTRICT_ID = VI.DISTRICT_ID AND MM.MANDAL_ID = VI.MANDAL_ID
                      AND MM.IS_ACTIVE = 'Y' AND MM.IS_MEPMA = 'N')
     GROUP BY VI.DISTRICT_ID, VI.MANDAL_ID, CONVERT(CHAR(7), BC.CREDITED_DATE, 120), MCP.PROJECT_TYPE
    OPTION (RECOMPILE);
END
