/* =====================================================================
   CEO Loan Intelligence Dashboard - stored procedure
   Designed and architected by CHINTALA MAHINDRA

   Procedure : dbo.USP_CEO_DASH_DRILL_SCOPE
   Java      : CeoLoanIntelligenceDAOImpl.drill()
   Replaces  : the inline SQL that CeoLoanIntelligenceDAOImpl.drill() used to run
   Runs      : a click at mandal, VO or SHG level (then cached until the next build)
   Returns   : one row per VO, SHG, woman, project, social category or purpose of the clicked place

   Level is taken from the most specific id given: @ShgId, else @VoId, else
   @MandalId (needs @DistrictId). Groups allowed: mandal VO / SHG / PROJECT /
   CATEGORY / PURPOSE; VO SHG / PROJECT / CATEGORY / PURPOSE; SHG MEMBER / PROJECT /
   CATEGORY / PURPOSE. SHG at mandal level returns the top 100 by collections with
   the VO as PARENT_ID. The women of the clicked place are read once into #X and
   their loans / repayments once into #L / #R; the result is the same as the
   inline version, which repeated that read inside each part of the query.

   Test in QueryTool / SSMS:
     EXEC dbo.USP_CEO_DASH_DRILL_SCOPE @Group = 'VO', @DistrictId = '07', @MandalId = '25',
          @From = '2026-04-01', @To = '2027-04-01', @SnOnly = 1, @PayModes = 1;
   ===================================================================== */

CREATE OR ALTER PROCEDURE dbo.USP_CEO_DASH_DRILL_SCOPE
    @Group VARCHAR(10),
    @DistrictId VARCHAR(10) = NULL,
    @MandalId VARCHAR(10) = NULL,
    @VoId VARCHAR(40) = NULL,
    @ShgId VARCHAR(40) = NULL,
    @From DATETIME,
    @To DATETIME,
    @ProjectType VARCHAR(20) = NULL,
    @SnOnly BIT = 1,
    @PayModes BIT = 1
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @Level VARCHAR(10) =
        CASE WHEN @ShgId IS NOT NULL THEN 'SHG' WHEN @VoId IS NOT NULL THEN 'VO'
             WHEN @MandalId IS NOT NULL THEN 'MANDAL' ELSE '' END;
    SET @Group = UPPER(LTRIM(RTRIM(@Group)));

    -- same checks as the Java code: allowed groups per level
    IF @Level = '' OR (@Level = 'MANDAL' AND @DistrictId IS NULL)
    BEGIN
        RAISERROR('give @MandalId with @DistrictId, or @VoId, or @ShgId', 16, 1);
        RETURN;
    END
    IF NOT ((@Level = 'MANDAL' AND @Group IN ('VO', 'SHG', 'PROJECT', 'CATEGORY', 'PURPOSE'))
         OR (@Level = 'VO'     AND @Group IN ('SHG', 'PROJECT', 'CATEGORY', 'PURPOSE'))
         OR (@Level = 'SHG'    AND @Group IN ('MEMBER', 'PROJECT', 'CATEGORY', 'PURPOSE')))
    BEGIN
        RAISERROR('group %s is not available at %s level', 16, 1, @Group, @Level);
        RETURN;
    END
    IF @From >= @To
    BEGIN
        RAISERROR('@From must be before @To', 16, 1);
        RETURN;
    END

    -- 1. active women of the clicked mandal / VO / SHG (column types copied from the source tables)
    SELECT TOP 0 MAX(SM.MEMBER_ID) AS MEMBER_ID, MAX(SM.MEMBER_NAME) AS MEMBER_NAME, MAX(SM.SHG_ID) AS SHG_ID,
           MAX(SI.VO_ID) AS VO_ID, MAX(SM.CATAGORY) AS CATEGORY
      INTO #X
      FROM SHG_MEMBER_INFO SM WITH (NOLOCK)
     CROSS JOIN SHG_INFO SI WITH (NOLOCK)
     WHERE 1 = 0;
    CREATE CLUSTERED INDEX IX_X ON #X (MEMBER_ID);

    IF @Level = 'MANDAL'
    BEGIN
        INSERT INTO #X (MEMBER_ID, MEMBER_NAME, SHG_ID, VO_ID, CATEGORY)
        SELECT SM.MEMBER_ID, MAX(SM.MEMBER_NAME), MAX(SM.SHG_ID), MAX(SI.VO_ID), MAX(SM.CATAGORY)
          FROM SHG_MEMBER_INFO SM WITH (NOLOCK)
         INNER JOIN SHG_INFO SI WITH (NOLOCK) ON SI.TRANS_SHG_ID = SM.SHG_ID AND SI.IS_ACTIVE = 'Y'
         INNER JOIN VO_INFO VI WITH (NOLOCK) ON VI.TRANS_VO_ID = SI.VO_ID AND VI.IS_ACTIVE = 'Y'
         WHERE SM.IS_MEM_ACTIVE = 'Y' AND LEN(LTRIM(RTRIM(SM.MEMBER_ID))) >= 20
           AND VI.DISTRICT_ID = @DistrictId AND VI.MANDAL_ID = @MandalId
           AND EXISTS (SELECT 1 FROM DISTRICT_MASTER DM WITH (NOLOCK)
                        WHERE DM.DISTRICT_ID = VI.DISTRICT_ID AND DM.FLAG = 'Y')
           AND EXISTS (SELECT 1 FROM MANDAL_MASTER MM WITH (NOLOCK)
                        WHERE MM.DISTRICT_ID = VI.DISTRICT_ID AND MM.MANDAL_ID = VI.MANDAL_ID
                          AND MM.IS_ACTIVE = 'Y' AND MM.IS_MEPMA = 'N')
         GROUP BY SM.MEMBER_ID
        OPTION (RECOMPILE);
    END
    ELSE IF @Level = 'VO'
    BEGIN
        INSERT INTO #X (MEMBER_ID, MEMBER_NAME, SHG_ID, VO_ID, CATEGORY)
        SELECT SM.MEMBER_ID, MAX(SM.MEMBER_NAME), MAX(SM.SHG_ID), MAX(SI.VO_ID), MAX(SM.CATAGORY)
          FROM SHG_MEMBER_INFO SM WITH (NOLOCK)
         INNER JOIN SHG_INFO SI WITH (NOLOCK) ON SI.TRANS_SHG_ID = SM.SHG_ID AND SI.IS_ACTIVE = 'Y'
         INNER JOIN VO_INFO VI WITH (NOLOCK) ON VI.TRANS_VO_ID = SI.VO_ID AND VI.IS_ACTIVE = 'Y'
         WHERE SM.IS_MEM_ACTIVE = 'Y' AND LEN(LTRIM(RTRIM(SM.MEMBER_ID))) >= 20
           AND VI.TRANS_VO_ID = @VoId
           AND EXISTS (SELECT 1 FROM DISTRICT_MASTER DM WITH (NOLOCK)
                        WHERE DM.DISTRICT_ID = VI.DISTRICT_ID AND DM.FLAG = 'Y')
           AND EXISTS (SELECT 1 FROM MANDAL_MASTER MM WITH (NOLOCK)
                        WHERE MM.DISTRICT_ID = VI.DISTRICT_ID AND MM.MANDAL_ID = VI.MANDAL_ID
                          AND MM.IS_ACTIVE = 'Y' AND MM.IS_MEPMA = 'N')
         GROUP BY SM.MEMBER_ID
        OPTION (RECOMPILE);
    END
    ELSE
    BEGIN
        INSERT INTO #X (MEMBER_ID, MEMBER_NAME, SHG_ID, VO_ID, CATEGORY)
        SELECT SM.MEMBER_ID, MAX(SM.MEMBER_NAME), MAX(SM.SHG_ID), MAX(SI.VO_ID), MAX(SM.CATAGORY)
          FROM SHG_MEMBER_INFO SM WITH (NOLOCK)
         INNER JOIN SHG_INFO SI WITH (NOLOCK) ON SI.TRANS_SHG_ID = SM.SHG_ID AND SI.IS_ACTIVE = 'Y'
         INNER JOIN VO_INFO VI WITH (NOLOCK) ON VI.TRANS_VO_ID = SI.VO_ID AND VI.IS_ACTIVE = 'Y'
         WHERE SM.IS_MEM_ACTIVE = 'Y' AND LEN(LTRIM(RTRIM(SM.MEMBER_ID))) >= 20
           AND SM.SHG_ID = @ShgId
           AND EXISTS (SELECT 1 FROM DISTRICT_MASTER DM WITH (NOLOCK)
                        WHERE DM.DISTRICT_ID = VI.DISTRICT_ID AND DM.FLAG = 'Y')
           AND EXISTS (SELECT 1 FROM MANDAL_MASTER MM WITH (NOLOCK)
                        WHERE MM.DISTRICT_ID = VI.DISTRICT_ID AND MM.MANDAL_ID = VI.MANDAL_ID
                          AND MM.IS_ACTIVE = 'Y' AND MM.IS_MEPMA = 'N')
         GROUP BY SM.MEMBER_ID
        OPTION (RECOMPILE);
    END

    -- 2. their valid loans issued in the period
    SELECT X.MEMBER_ID, X.VO_ID, X.SHG_ID, X.CATEGORY, MCP.PROJECT_TYPE,
           ISNULL(UPPER(NULLIF(LTRIM(RTRIM(MCP.PURPOSE)), '')), '') AS PURPOSE_N,
           MCP.LOAN_STATUS, MCP.LOAN_AMOUNT_ISSUED
      INTO #L
      FROM SHG_MEMBER_MCP_INFO MCP WITH (NOLOCK)
     INNER JOIN #X X ON X.MEMBER_ID = MCP.MEMBER_LONG_CODE
     WHERE MCP.ISSUED_DATE >= @From AND MCP.ISSUED_DATE < @To
       AND MCP.MEMBER_LONG_CODE IS NOT NULL
       AND LTRIM(RTRIM(MCP.MEMBER_LONG_CODE)) <> ''
       AND LEN(MCP.MEMBER_LONG_CODE) >= 20
       AND MCP.ISSUED_DATE IS NOT NULL
       AND MCP.ISSUED_DATE > '2000-01-01'
       AND MCP.LOAN_STATUS IN ('OPEN', 'CLOSED')
       AND (@SnOnly = 0 OR MCP.PROJECT_TYPE IN (SELECT PROJECT_TYPE FROM PROJECT_TYPE_LOAN_MAPPING WITH (NOLOCK)
                                                WHERE LTRIM(RTRIM(LOAN_TYPE)) = 'SN'))
       AND (@ProjectType IS NULL OR MCP.PROJECT_TYPE = @ProjectType)
    OPTION (RECOMPILE);

    -- 3. their repayments credited in the period (bank credit arrived, VO credit CLOSED)
    SELECT X.MEMBER_ID, X.VO_ID, X.SHG_ID, X.CATEGORY, MCP.PROJECT_TYPE,
           ISNULL(UPPER(NULLIF(LTRIM(RTRIM(MCP.PURPOSE)), '')), '') AS PURPOSE_N,
           SCI.REPAID_AMOUNT, PM.MODE_CODE
      INTO #R
      FROM SHG_CREDIT_INFO SCI WITH (NOLOCK)
     INNER JOIN (SELECT BCI.BANK_REF_NO, MIN(BCI.CREDITED_DATE) AS CREDITED_DATE
                   FROM BANKS_CREDIT_INFO BCI WITH (NOLOCK)
                  WHERE BCI.CREDITED_DATE >= @From AND BCI.CREDITED_DATE < @To
                    AND BCI.BANK_REF_NO IS NOT NULL
                  GROUP BY BCI.BANK_REF_NO) BC ON BC.BANK_REF_NO = SCI.BANK_REF_NO
     INNER JOIN (SELECT VC.BANK_REF_NO,
                        MAX(CASE WHEN VC.CREATED_BY = 'PAYTM PAYMENT SERVICE'  THEN 3
                                 WHEN VC.CREATED_BY = 'Phi PAYMENT SERVICE'    THEN 2
                                 WHEN VC.CREATED_BY = 'SHG AUTO DEBIT PROCESS' THEN 1 ELSE 0 END) AS MODE_CODE,
                        MAX(VC.CREATED_BY) AS CB
                   FROM VO_CREDIT_INFO VC WITH (NOLOCK)
                  WHERE VC.BANK_REF_NO IS NOT NULL AND VC.VO_REPAY_STATUS = 'CLOSED'
                  GROUP BY VC.BANK_REF_NO) PM ON PM.BANK_REF_NO = SCI.BANK_REF_NO
     INNER JOIN SHG_MEMBER_MCP_INFO MCP WITH (NOLOCK) ON MCP.SHG_MEMBER_LOAN_ACCNO = SCI.SHG_MEMBER_LOAN_ACCNO
     INNER JOIN #X X ON X.MEMBER_ID = MCP.MEMBER_LONG_CODE
     WHERE SCI.SHG_MEMBER_LOAN_ACCNO <> ''
       AND MCP.MEMBER_LONG_CODE IS NOT NULL
       AND LTRIM(RTRIM(MCP.MEMBER_LONG_CODE)) <> ''
       AND LEN(MCP.MEMBER_LONG_CODE) >= 20
       AND MCP.ISSUED_DATE IS NOT NULL
       AND MCP.ISSUED_DATE > '2000-01-01'
       AND MCP.LOAN_STATUS IN ('OPEN', 'CLOSED')
       AND (@SnOnly = 0 OR MCP.PROJECT_TYPE IN (SELECT PROJECT_TYPE FROM PROJECT_TYPE_LOAN_MAPPING WITH (NOLOCK)
                                                WHERE LTRIM(RTRIM(LOAN_TYPE)) = 'SN'))
       AND (@ProjectType IS NULL OR MCP.PROJECT_TYPE = @ProjectType)
    OPTION (RECOMPILE);

    -- 4. one row per unit of the requested group
    IF @Group = 'VO'
    BEGIN
        SELECT U.UNIT_ID, U.UNIT_NAME, ISNULL(M.ACTIVE_MEMBERS, 0) AS ACTIVE_MEMBERS,
               ISNULL(L.LOAN_COUNT, 0) AS LOAN_COUNT, ISNULL(L.DISBURSED_AMOUNT, 0) AS DISBURSED_AMOUNT,
               ISNULL(L.OPEN_LOAN_COUNT, 0) AS OPEN_LOAN_COUNT, ISNULL(L.CLOSED_LOAN_COUNT, 0) AS CLOSED_LOAN_COUNT,
               ISNULL(L.OPEN_AMOUNT, 0) AS OPEN_AMOUNT, ISNULL(L.BORROWERS, 0) AS BORROWERS,
               ISNULL(R.REPAYMENT_TXN_COUNT, 0) AS REPAYMENT_TXN_COUNT, ISNULL(R.REPAID_AMOUNT, 0) AS REPAID_AMOUNT,
               ISNULL(R.PAYERS, 0) AS PAYERS,
               ISNULL(R.REPAID_POS, 0) AS REPAID_POS, ISNULL(R.REPAID_UPI, 0) AS REPAID_UPI, ISNULL(R.REPAID_AUTO, 0) AS REPAID_AUTO,
               ISNULL(R.TXNS_POS, 0) AS TXNS_POS, ISNULL(R.TXNS_UPI, 0) AS TXNS_UPI, ISNULL(R.TXNS_AUTO, 0) AS TXNS_AUTO
          FROM (
                SELECT VI.TRANS_VO_ID AS UNIT_ID, MAX(VI.VO_NAME) AS UNIT_NAME
                  FROM VO_INFO VI WITH (NOLOCK)
                 WHERE VI.IS_ACTIVE = 'Y'
                   AND VI.DISTRICT_ID = @DistrictId AND VI.MANDAL_ID = @MandalId
                 GROUP BY VI.TRANS_VO_ID
               ) U
          LEFT JOIN (
                SELECT VO_ID AS UNIT_ID, COUNT(*) AS ACTIVE_MEMBERS FROM #X GROUP BY VO_ID
               ) M ON M.UNIT_ID = U.UNIT_ID
          LEFT JOIN (
                SELECT VO_ID AS UNIT_ID, COUNT(*) AS LOAN_COUNT,
                       SUM(LOAN_AMOUNT_ISSUED) AS DISBURSED_AMOUNT,
                       SUM(CASE WHEN LOAN_STATUS = 'OPEN' THEN 1 ELSE 0 END) AS OPEN_LOAN_COUNT,
                       SUM(CASE WHEN LOAN_STATUS = 'CLOSED' THEN 1 ELSE 0 END) AS CLOSED_LOAN_COUNT,
                       SUM(CASE WHEN LOAN_STATUS = 'OPEN' THEN LOAN_AMOUNT_ISSUED ELSE 0 END) AS OPEN_AMOUNT,
                       COUNT(DISTINCT MEMBER_ID) AS BORROWERS
                  FROM #L
                 GROUP BY VO_ID
               ) L ON L.UNIT_ID = U.UNIT_ID
          LEFT JOIN (
                SELECT VO_ID AS UNIT_ID, COUNT(*) AS REPAYMENT_TXN_COUNT,
                       SUM(REPAID_AMOUNT) AS REPAID_AMOUNT,
                       COUNT(DISTINCT MEMBER_ID) AS PAYERS,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 3 THEN REPAID_AMOUNT ELSE 0 END) AS REPAID_POS,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 2 THEN REPAID_AMOUNT ELSE 0 END) AS REPAID_UPI,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 1 THEN REPAID_AMOUNT ELSE 0 END) AS REPAID_AUTO,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 3 THEN 1 ELSE 0 END) AS TXNS_POS,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 2 THEN 1 ELSE 0 END) AS TXNS_UPI,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 1 THEN 1 ELSE 0 END) AS TXNS_AUTO
                  FROM #R
                 GROUP BY VO_ID
               ) R ON R.UNIT_ID = U.UNIT_ID
         ORDER BY U.UNIT_NAME
        OPTION (RECOMPILE);
        RETURN;
    END

    IF @Group = 'SHG' AND @Level = 'MANDAL'
    BEGIN
        -- SHGs of a whole mandal: only the 100 with the highest collections
        SELECT TOP 100 U.PARENT_ID, U.UNIT_ID, U.UNIT_NAME, ISNULL(M.ACTIVE_MEMBERS, 0) AS ACTIVE_MEMBERS,
               ISNULL(L.LOAN_COUNT, 0) AS LOAN_COUNT, ISNULL(L.DISBURSED_AMOUNT, 0) AS DISBURSED_AMOUNT,
               ISNULL(L.OPEN_LOAN_COUNT, 0) AS OPEN_LOAN_COUNT, ISNULL(L.CLOSED_LOAN_COUNT, 0) AS CLOSED_LOAN_COUNT,
               ISNULL(L.OPEN_AMOUNT, 0) AS OPEN_AMOUNT, ISNULL(L.BORROWERS, 0) AS BORROWERS,
               ISNULL(R.REPAYMENT_TXN_COUNT, 0) AS REPAYMENT_TXN_COUNT, ISNULL(R.REPAID_AMOUNT, 0) AS REPAID_AMOUNT,
               ISNULL(R.PAYERS, 0) AS PAYERS,
               ISNULL(R.REPAID_POS, 0) AS REPAID_POS, ISNULL(R.REPAID_UPI, 0) AS REPAID_UPI, ISNULL(R.REPAID_AUTO, 0) AS REPAID_AUTO,
               ISNULL(R.TXNS_POS, 0) AS TXNS_POS, ISNULL(R.TXNS_UPI, 0) AS TXNS_UPI, ISNULL(R.TXNS_AUTO, 0) AS TXNS_AUTO
          FROM (
                SELECT SI.TRANS_SHG_ID AS UNIT_ID, MAX(SI.SHG_NAME) AS UNIT_NAME, MAX(SI.VO_ID) AS PARENT_ID
                  FROM SHG_INFO SI WITH (NOLOCK)
                 INNER JOIN VO_INFO VI WITH (NOLOCK) ON VI.TRANS_VO_ID = SI.VO_ID AND VI.IS_ACTIVE = 'Y'
                 WHERE SI.IS_ACTIVE = 'Y'
                   AND VI.DISTRICT_ID = @DistrictId AND VI.MANDAL_ID = @MandalId
                 GROUP BY SI.TRANS_SHG_ID
               ) U
          LEFT JOIN (
                SELECT SHG_ID AS UNIT_ID, COUNT(*) AS ACTIVE_MEMBERS FROM #X GROUP BY SHG_ID
               ) M ON M.UNIT_ID = U.UNIT_ID
          LEFT JOIN (
                SELECT SHG_ID AS UNIT_ID, COUNT(*) AS LOAN_COUNT,
                       SUM(LOAN_AMOUNT_ISSUED) AS DISBURSED_AMOUNT,
                       SUM(CASE WHEN LOAN_STATUS = 'OPEN' THEN 1 ELSE 0 END) AS OPEN_LOAN_COUNT,
                       SUM(CASE WHEN LOAN_STATUS = 'CLOSED' THEN 1 ELSE 0 END) AS CLOSED_LOAN_COUNT,
                       SUM(CASE WHEN LOAN_STATUS = 'OPEN' THEN LOAN_AMOUNT_ISSUED ELSE 0 END) AS OPEN_AMOUNT,
                       COUNT(DISTINCT MEMBER_ID) AS BORROWERS
                  FROM #L
                 GROUP BY SHG_ID
               ) L ON L.UNIT_ID = U.UNIT_ID
          LEFT JOIN (
                SELECT SHG_ID AS UNIT_ID, COUNT(*) AS REPAYMENT_TXN_COUNT,
                       SUM(REPAID_AMOUNT) AS REPAID_AMOUNT,
                       COUNT(DISTINCT MEMBER_ID) AS PAYERS,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 3 THEN REPAID_AMOUNT ELSE 0 END) AS REPAID_POS,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 2 THEN REPAID_AMOUNT ELSE 0 END) AS REPAID_UPI,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 1 THEN REPAID_AMOUNT ELSE 0 END) AS REPAID_AUTO,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 3 THEN 1 ELSE 0 END) AS TXNS_POS,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 2 THEN 1 ELSE 0 END) AS TXNS_UPI,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 1 THEN 1 ELSE 0 END) AS TXNS_AUTO
                  FROM #R
                 GROUP BY SHG_ID
               ) R ON R.UNIT_ID = U.UNIT_ID
         ORDER BY ISNULL(R.REPAID_AMOUNT, 0) DESC, ISNULL(L.DISBURSED_AMOUNT, 0) DESC
        OPTION (RECOMPILE);
        RETURN;
    END

    IF @Group = 'SHG'
    BEGIN
        SELECT U.UNIT_ID, U.UNIT_NAME, ISNULL(M.ACTIVE_MEMBERS, 0) AS ACTIVE_MEMBERS,
               ISNULL(L.LOAN_COUNT, 0) AS LOAN_COUNT, ISNULL(L.DISBURSED_AMOUNT, 0) AS DISBURSED_AMOUNT,
               ISNULL(L.OPEN_LOAN_COUNT, 0) AS OPEN_LOAN_COUNT, ISNULL(L.CLOSED_LOAN_COUNT, 0) AS CLOSED_LOAN_COUNT,
               ISNULL(L.OPEN_AMOUNT, 0) AS OPEN_AMOUNT, ISNULL(L.BORROWERS, 0) AS BORROWERS,
               ISNULL(R.REPAYMENT_TXN_COUNT, 0) AS REPAYMENT_TXN_COUNT, ISNULL(R.REPAID_AMOUNT, 0) AS REPAID_AMOUNT,
               ISNULL(R.PAYERS, 0) AS PAYERS,
               ISNULL(R.REPAID_POS, 0) AS REPAID_POS, ISNULL(R.REPAID_UPI, 0) AS REPAID_UPI, ISNULL(R.REPAID_AUTO, 0) AS REPAID_AUTO,
               ISNULL(R.TXNS_POS, 0) AS TXNS_POS, ISNULL(R.TXNS_UPI, 0) AS TXNS_UPI, ISNULL(R.TXNS_AUTO, 0) AS TXNS_AUTO
          FROM (
                SELECT SI.TRANS_SHG_ID AS UNIT_ID, MAX(SI.SHG_NAME) AS UNIT_NAME
                  FROM SHG_INFO SI WITH (NOLOCK)
                 WHERE SI.IS_ACTIVE = 'Y'
                   AND SI.VO_ID = @VoId
                 GROUP BY SI.TRANS_SHG_ID
               ) U
          LEFT JOIN (
                SELECT SHG_ID AS UNIT_ID, COUNT(*) AS ACTIVE_MEMBERS FROM #X GROUP BY SHG_ID
               ) M ON M.UNIT_ID = U.UNIT_ID
          LEFT JOIN (
                SELECT SHG_ID AS UNIT_ID, COUNT(*) AS LOAN_COUNT,
                       SUM(LOAN_AMOUNT_ISSUED) AS DISBURSED_AMOUNT,
                       SUM(CASE WHEN LOAN_STATUS = 'OPEN' THEN 1 ELSE 0 END) AS OPEN_LOAN_COUNT,
                       SUM(CASE WHEN LOAN_STATUS = 'CLOSED' THEN 1 ELSE 0 END) AS CLOSED_LOAN_COUNT,
                       SUM(CASE WHEN LOAN_STATUS = 'OPEN' THEN LOAN_AMOUNT_ISSUED ELSE 0 END) AS OPEN_AMOUNT,
                       COUNT(DISTINCT MEMBER_ID) AS BORROWERS
                  FROM #L
                 GROUP BY SHG_ID
               ) L ON L.UNIT_ID = U.UNIT_ID
          LEFT JOIN (
                SELECT SHG_ID AS UNIT_ID, COUNT(*) AS REPAYMENT_TXN_COUNT,
                       SUM(REPAID_AMOUNT) AS REPAID_AMOUNT,
                       COUNT(DISTINCT MEMBER_ID) AS PAYERS,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 3 THEN REPAID_AMOUNT ELSE 0 END) AS REPAID_POS,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 2 THEN REPAID_AMOUNT ELSE 0 END) AS REPAID_UPI,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 1 THEN REPAID_AMOUNT ELSE 0 END) AS REPAID_AUTO,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 3 THEN 1 ELSE 0 END) AS TXNS_POS,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 2 THEN 1 ELSE 0 END) AS TXNS_UPI,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 1 THEN 1 ELSE 0 END) AS TXNS_AUTO
                  FROM #R
                 GROUP BY SHG_ID
               ) R ON R.UNIT_ID = U.UNIT_ID
         ORDER BY U.UNIT_NAME
        OPTION (RECOMPILE);
        RETURN;
    END

    IF @Group = 'MEMBER'
    BEGIN
        SELECT U.UNIT_ID, U.UNIT_NAME, 1 AS ACTIVE_MEMBERS,
               ISNULL(L.LOAN_COUNT, 0) AS LOAN_COUNT, ISNULL(L.DISBURSED_AMOUNT, 0) AS DISBURSED_AMOUNT,
               ISNULL(L.OPEN_LOAN_COUNT, 0) AS OPEN_LOAN_COUNT, ISNULL(L.CLOSED_LOAN_COUNT, 0) AS CLOSED_LOAN_COUNT,
               ISNULL(L.OPEN_AMOUNT, 0) AS OPEN_AMOUNT, ISNULL(L.BORROWERS, 0) AS BORROWERS,
               ISNULL(R.REPAYMENT_TXN_COUNT, 0) AS REPAYMENT_TXN_COUNT, ISNULL(R.REPAID_AMOUNT, 0) AS REPAID_AMOUNT,
               ISNULL(R.PAYERS, 0) AS PAYERS,
               ISNULL(R.REPAID_POS, 0) AS REPAID_POS, ISNULL(R.REPAID_UPI, 0) AS REPAID_UPI, ISNULL(R.REPAID_AUTO, 0) AS REPAID_AUTO,
               ISNULL(R.TXNS_POS, 0) AS TXNS_POS, ISNULL(R.TXNS_UPI, 0) AS TXNS_UPI, ISNULL(R.TXNS_AUTO, 0) AS TXNS_AUTO
          FROM (
                SELECT X.MEMBER_ID AS UNIT_ID, X.MEMBER_NAME AS UNIT_NAME
                  FROM #X X
               ) U
          LEFT JOIN (
                SELECT MEMBER_ID AS UNIT_ID, COUNT(*) AS LOAN_COUNT,
                       SUM(LOAN_AMOUNT_ISSUED) AS DISBURSED_AMOUNT,
                       SUM(CASE WHEN LOAN_STATUS = 'OPEN' THEN 1 ELSE 0 END) AS OPEN_LOAN_COUNT,
                       SUM(CASE WHEN LOAN_STATUS = 'CLOSED' THEN 1 ELSE 0 END) AS CLOSED_LOAN_COUNT,
                       SUM(CASE WHEN LOAN_STATUS = 'OPEN' THEN LOAN_AMOUNT_ISSUED ELSE 0 END) AS OPEN_AMOUNT,
                       COUNT(DISTINCT MEMBER_ID) AS BORROWERS
                  FROM #L
                 GROUP BY MEMBER_ID
               ) L ON L.UNIT_ID = U.UNIT_ID
          LEFT JOIN (
                SELECT MEMBER_ID AS UNIT_ID, COUNT(*) AS REPAYMENT_TXN_COUNT,
                       SUM(REPAID_AMOUNT) AS REPAID_AMOUNT,
                       COUNT(DISTINCT MEMBER_ID) AS PAYERS,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 3 THEN REPAID_AMOUNT ELSE 0 END) AS REPAID_POS,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 2 THEN REPAID_AMOUNT ELSE 0 END) AS REPAID_UPI,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 1 THEN REPAID_AMOUNT ELSE 0 END) AS REPAID_AUTO,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 3 THEN 1 ELSE 0 END) AS TXNS_POS,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 2 THEN 1 ELSE 0 END) AS TXNS_UPI,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 1 THEN 1 ELSE 0 END) AS TXNS_AUTO
                  FROM #R
                 GROUP BY MEMBER_ID
               ) R ON R.UNIT_ID = U.UNIT_ID
         ORDER BY U.UNIT_NAME
        OPTION (RECOMPILE);
        RETURN;
    END

    IF @Group = 'PROJECT'
    BEGIN
        SELECT COALESCE(L.UNIT_ID, R.UNIT_ID) AS UNIT_ID, MAX(PT.PROJECT_NAME) AS UNIT_NAME,
               CAST(NULL AS INT) AS ACTIVE_MEMBERS,
               MAX(ISNULL(L.LOAN_COUNT, 0)) AS LOAN_COUNT, MAX(ISNULL(L.DISBURSED_AMOUNT, 0)) AS DISBURSED_AMOUNT,
               MAX(ISNULL(L.OPEN_LOAN_COUNT, 0)) AS OPEN_LOAN_COUNT, MAX(ISNULL(L.CLOSED_LOAN_COUNT, 0)) AS CLOSED_LOAN_COUNT,
               MAX(ISNULL(L.OPEN_AMOUNT, 0)) AS OPEN_AMOUNT,
               MAX(ISNULL(L.BORROWERS, 0)) AS BORROWERS,
               MAX(ISNULL(R.REPAYMENT_TXN_COUNT, 0)) AS REPAYMENT_TXN_COUNT, MAX(ISNULL(R.REPAID_AMOUNT, 0)) AS REPAID_AMOUNT,
               MAX(ISNULL(R.PAYERS, 0)) AS PAYERS,
               MAX(ISNULL(R.REPAID_POS, 0)) AS REPAID_POS, MAX(ISNULL(R.REPAID_UPI, 0)) AS REPAID_UPI,
               MAX(ISNULL(R.REPAID_AUTO, 0)) AS REPAID_AUTO, MAX(ISNULL(R.TXNS_POS, 0)) AS TXNS_POS,
               MAX(ISNULL(R.TXNS_UPI, 0)) AS TXNS_UPI, MAX(ISNULL(R.TXNS_AUTO, 0)) AS TXNS_AUTO
          FROM (
                SELECT PROJECT_TYPE AS UNIT_ID, COUNT(*) AS LOAN_COUNT,
                       SUM(LOAN_AMOUNT_ISSUED) AS DISBURSED_AMOUNT,
                       SUM(CASE WHEN LOAN_STATUS = 'OPEN' THEN 1 ELSE 0 END) AS OPEN_LOAN_COUNT,
                       SUM(CASE WHEN LOAN_STATUS = 'CLOSED' THEN 1 ELSE 0 END) AS CLOSED_LOAN_COUNT,
                       SUM(CASE WHEN LOAN_STATUS = 'OPEN' THEN LOAN_AMOUNT_ISSUED ELSE 0 END) AS OPEN_AMOUNT,
                       COUNT(DISTINCT MEMBER_ID) AS BORROWERS
                  FROM #L
                 GROUP BY PROJECT_TYPE
               ) L
          FULL OUTER JOIN (
                SELECT PROJECT_TYPE AS UNIT_ID, COUNT(*) AS REPAYMENT_TXN_COUNT,
                       SUM(REPAID_AMOUNT) AS REPAID_AMOUNT,
                       COUNT(DISTINCT MEMBER_ID) AS PAYERS,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 3 THEN REPAID_AMOUNT ELSE 0 END) AS REPAID_POS,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 2 THEN REPAID_AMOUNT ELSE 0 END) AS REPAID_UPI,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 1 THEN REPAID_AMOUNT ELSE 0 END) AS REPAID_AUTO,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 3 THEN 1 ELSE 0 END) AS TXNS_POS,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 2 THEN 1 ELSE 0 END) AS TXNS_UPI,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 1 THEN 1 ELSE 0 END) AS TXNS_AUTO
                  FROM #R
                 GROUP BY PROJECT_TYPE
               ) R ON R.UNIT_ID = L.UNIT_ID
          LEFT JOIN (SELECT PROJECT_TYPE, MAX(PROJECT_NAME) AS PROJECT_NAME
                       FROM PROJECT_TYPE_LOAN_MAPPING WITH (NOLOCK)
                      WHERE (@SnOnly = 0 OR LTRIM(RTRIM(LOAN_TYPE)) = 'SN')
                      GROUP BY PROJECT_TYPE) PT ON PT.PROJECT_TYPE = COALESCE(L.UNIT_ID, R.UNIT_ID)
         GROUP BY COALESCE(L.UNIT_ID, R.UNIT_ID)
        OPTION (RECOMPILE);
        RETURN;
    END

    IF @Group = 'CATEGORY'
    BEGIN
        SELECT COALESCE(L.UNIT_ID, R.UNIT_ID) AS UNIT_ID, COALESCE(L.UNIT_ID, R.UNIT_ID) AS UNIT_NAME,
               CAST(NULL AS INT) AS ACTIVE_MEMBERS,
               MAX(ISNULL(L.LOAN_COUNT, 0)) AS LOAN_COUNT, MAX(ISNULL(L.DISBURSED_AMOUNT, 0)) AS DISBURSED_AMOUNT,
               MAX(ISNULL(L.OPEN_LOAN_COUNT, 0)) AS OPEN_LOAN_COUNT, MAX(ISNULL(L.CLOSED_LOAN_COUNT, 0)) AS CLOSED_LOAN_COUNT,
               MAX(ISNULL(L.OPEN_AMOUNT, 0)) AS OPEN_AMOUNT,
               MAX(ISNULL(L.BORROWERS, 0)) AS BORROWERS,
               MAX(ISNULL(R.REPAYMENT_TXN_COUNT, 0)) AS REPAYMENT_TXN_COUNT, MAX(ISNULL(R.REPAID_AMOUNT, 0)) AS REPAID_AMOUNT,
               MAX(ISNULL(R.PAYERS, 0)) AS PAYERS,
               MAX(ISNULL(R.REPAID_POS, 0)) AS REPAID_POS, MAX(ISNULL(R.REPAID_UPI, 0)) AS REPAID_UPI,
               MAX(ISNULL(R.REPAID_AUTO, 0)) AS REPAID_AUTO, MAX(ISNULL(R.TXNS_POS, 0)) AS TXNS_POS,
               MAX(ISNULL(R.TXNS_UPI, 0)) AS TXNS_UPI, MAX(ISNULL(R.TXNS_AUTO, 0)) AS TXNS_AUTO
          FROM (
                SELECT UPPER(LTRIM(RTRIM(ISNULL(CATEGORY, '')))) AS UNIT_ID, COUNT(*) AS LOAN_COUNT,
                       SUM(LOAN_AMOUNT_ISSUED) AS DISBURSED_AMOUNT,
                       SUM(CASE WHEN LOAN_STATUS = 'OPEN' THEN 1 ELSE 0 END) AS OPEN_LOAN_COUNT,
                       SUM(CASE WHEN LOAN_STATUS = 'CLOSED' THEN 1 ELSE 0 END) AS CLOSED_LOAN_COUNT,
                       SUM(CASE WHEN LOAN_STATUS = 'OPEN' THEN LOAN_AMOUNT_ISSUED ELSE 0 END) AS OPEN_AMOUNT,
                       COUNT(DISTINCT MEMBER_ID) AS BORROWERS
                  FROM #L
                 GROUP BY UPPER(LTRIM(RTRIM(ISNULL(CATEGORY, ''))))
               ) L
          FULL OUTER JOIN (
                SELECT UPPER(LTRIM(RTRIM(ISNULL(CATEGORY, '')))) AS UNIT_ID, COUNT(*) AS REPAYMENT_TXN_COUNT,
                       SUM(REPAID_AMOUNT) AS REPAID_AMOUNT,
                       COUNT(DISTINCT MEMBER_ID) AS PAYERS,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 3 THEN REPAID_AMOUNT ELSE 0 END) AS REPAID_POS,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 2 THEN REPAID_AMOUNT ELSE 0 END) AS REPAID_UPI,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 1 THEN REPAID_AMOUNT ELSE 0 END) AS REPAID_AUTO,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 3 THEN 1 ELSE 0 END) AS TXNS_POS,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 2 THEN 1 ELSE 0 END) AS TXNS_UPI,
                       SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 1 THEN 1 ELSE 0 END) AS TXNS_AUTO
                  FROM #R
                 GROUP BY UPPER(LTRIM(RTRIM(ISNULL(CATEGORY, ''))))
               ) R ON R.UNIT_ID = L.UNIT_ID
         GROUP BY COALESCE(L.UNIT_ID, R.UNIT_ID)
        OPTION (RECOMPILE);
        RETURN;
    END

    -- PURPOSE
    SELECT COALESCE(L.UNIT_ID, R.UNIT_ID) AS UNIT_ID, COALESCE(L.UNIT_ID, R.UNIT_ID) AS UNIT_NAME,
           CAST(NULL AS INT) AS ACTIVE_MEMBERS,
           MAX(ISNULL(L.LOAN_COUNT, 0)) AS LOAN_COUNT, MAX(ISNULL(L.DISBURSED_AMOUNT, 0)) AS DISBURSED_AMOUNT,
           MAX(ISNULL(L.OPEN_LOAN_COUNT, 0)) AS OPEN_LOAN_COUNT, MAX(ISNULL(L.CLOSED_LOAN_COUNT, 0)) AS CLOSED_LOAN_COUNT,
           MAX(ISNULL(L.OPEN_AMOUNT, 0)) AS OPEN_AMOUNT,
           MAX(ISNULL(L.BORROWERS, 0)) AS BORROWERS,
           MAX(ISNULL(R.REPAYMENT_TXN_COUNT, 0)) AS REPAYMENT_TXN_COUNT, MAX(ISNULL(R.REPAID_AMOUNT, 0)) AS REPAID_AMOUNT,
           MAX(ISNULL(R.PAYERS, 0)) AS PAYERS,
           MAX(ISNULL(R.REPAID_POS, 0)) AS REPAID_POS, MAX(ISNULL(R.REPAID_UPI, 0)) AS REPAID_UPI,
           MAX(ISNULL(R.REPAID_AUTO, 0)) AS REPAID_AUTO, MAX(ISNULL(R.TXNS_POS, 0)) AS TXNS_POS,
           MAX(ISNULL(R.TXNS_UPI, 0)) AS TXNS_UPI, MAX(ISNULL(R.TXNS_AUTO, 0)) AS TXNS_AUTO
      FROM (
            SELECT PURPOSE_N AS UNIT_ID, COUNT(*) AS LOAN_COUNT,
                   SUM(LOAN_AMOUNT_ISSUED) AS DISBURSED_AMOUNT,
                   SUM(CASE WHEN LOAN_STATUS = 'OPEN' THEN 1 ELSE 0 END) AS OPEN_LOAN_COUNT,
                   SUM(CASE WHEN LOAN_STATUS = 'CLOSED' THEN 1 ELSE 0 END) AS CLOSED_LOAN_COUNT,
                   SUM(CASE WHEN LOAN_STATUS = 'OPEN' THEN LOAN_AMOUNT_ISSUED ELSE 0 END) AS OPEN_AMOUNT,
                   COUNT(DISTINCT MEMBER_ID) AS BORROWERS
              FROM #L
             GROUP BY PURPOSE_N
           ) L
      FULL OUTER JOIN (
            SELECT PURPOSE_N AS UNIT_ID, COUNT(*) AS REPAYMENT_TXN_COUNT,
                   SUM(REPAID_AMOUNT) AS REPAID_AMOUNT,
                   COUNT(DISTINCT MEMBER_ID) AS PAYERS,
                   SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 3 THEN REPAID_AMOUNT ELSE 0 END) AS REPAID_POS,
                   SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 2 THEN REPAID_AMOUNT ELSE 0 END) AS REPAID_UPI,
                   SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 1 THEN REPAID_AMOUNT ELSE 0 END) AS REPAID_AUTO,
                   SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 3 THEN 1 ELSE 0 END) AS TXNS_POS,
                   SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 2 THEN 1 ELSE 0 END) AS TXNS_UPI,
                   SUM(CASE WHEN @PayModes = 1 AND MODE_CODE = 1 THEN 1 ELSE 0 END) AS TXNS_AUTO
              FROM #R
             GROUP BY PURPOSE_N
           ) R ON R.UNIT_ID = L.UNIT_ID
     GROUP BY COALESCE(L.UNIT_ID, R.UNIT_ID)
    OPTION (RECOMPILE);
END
