/* =====================================================================
   CEO Loan Intelligence Dashboard - stored procedure
   Designed and architected by CHINTALA MAHINDRA

   Procedure : dbo.USP_CEO_DASH_MANDAL_OVERDUE
   Java      : CeoLoanIntelligenceDAOImpl.getMandalOverdueRollup()
   Replaces  : the inline SQL that CeoLoanIntelligenceDAOImpl.getMandalOverdueRollup() used to run
   Runs      : snapshot build
   Returns   : arrears per district / mandal of open loans: overdue loans and amount, outstanding, and three arrears bands

   Arrears come from SN.SHG_MEMBER_LOAN_STATUS_NEW (one row per loan, refreshed daily):
   LOAN_DUE = amount behind, LOAN_EMI = instalment, OUTSTANDING = balance.
   Bands: B1 arrears up to 1 instalment, B2 1 to 3, B3 over 3 (or no instalment left).
   The inline version could point at another table with -Dceo.dash.statusTable;
   the procedure always reads SN.SHG_MEMBER_LOAN_STATUS_NEW.

   Test in QueryTool / SSMS:
     EXEC dbo.USP_CEO_DASH_MANDAL_OVERDUE @SnOnly = 1;
   ===================================================================== */

CREATE OR ALTER PROCEDURE dbo.USP_CEO_DASH_MANDAL_OVERDUE
    @SnOnly BIT = 1
AS
BEGIN
    SET NOCOUNT ON;

    SELECT VI.DISTRICT_ID, VI.MANDAL_ID,
           COUNT(*) AS STATUS_LOANS,
           SUM(CASE WHEN ISNULL(S.LOAN_DUE, 0) > 0 THEN 1 ELSE 0 END) AS OVERDUE_LOANS,
           SUM(CASE WHEN ISNULL(S.LOAN_DUE, 0) > 0 THEN ISNULL(S.LOAN_DUE, 0) ELSE 0 END) AS OVERDUE_AMOUNT,
           SUM(CASE WHEN ISNULL(S.OUTSTANDING, 0) > 0 THEN ISNULL(S.OUTSTANDING, 0) ELSE 0 END) AS OUTSTANDING_AMOUNT,
           SUM(CASE WHEN ISNULL(S.LOAN_DUE, 0) > 0 AND ISNULL(S.OUTSTANDING, 0) > 0 THEN ISNULL(S.OUTSTANDING, 0) ELSE 0 END) AS OVERDUE_OUTSTANDING,
           SUM(CASE WHEN ISNULL(S.LOAN_DUE, 0) > 0 AND ISNULL(S.LOAN_EMI, 0) > 0 AND ISNULL(S.LOAN_DUE, 0) <= ISNULL(S.LOAN_EMI, 0) THEN 1 ELSE 0 END) AS B1_LOANS,
           SUM(CASE WHEN ISNULL(S.LOAN_DUE, 0) > 0 AND ISNULL(S.LOAN_EMI, 0) > 0 AND ISNULL(S.LOAN_DUE, 0) <= ISNULL(S.LOAN_EMI, 0) THEN ISNULL(S.LOAN_DUE, 0) ELSE 0 END) AS B1_AMOUNT,
           SUM(CASE WHEN ISNULL(S.LOAN_DUE, 0) > 0 AND ISNULL(S.LOAN_EMI, 0) > 0 AND ISNULL(S.LOAN_DUE, 0) > ISNULL(S.LOAN_EMI, 0) AND ISNULL(S.LOAN_DUE, 0) <= 3 * ISNULL(S.LOAN_EMI, 0) THEN 1 ELSE 0 END) AS B2_LOANS,
           SUM(CASE WHEN ISNULL(S.LOAN_DUE, 0) > 0 AND ISNULL(S.LOAN_EMI, 0) > 0 AND ISNULL(S.LOAN_DUE, 0) > ISNULL(S.LOAN_EMI, 0) AND ISNULL(S.LOAN_DUE, 0) <= 3 * ISNULL(S.LOAN_EMI, 0) THEN ISNULL(S.LOAN_DUE, 0) ELSE 0 END) AS B2_AMOUNT,
           SUM(CASE WHEN ISNULL(S.LOAN_DUE, 0) > 0 AND (ISNULL(S.LOAN_EMI, 0) <= 0 OR ISNULL(S.LOAN_DUE, 0) > 3 * ISNULL(S.LOAN_EMI, 0)) THEN 1 ELSE 0 END) AS B3_LOANS,
           SUM(CASE WHEN ISNULL(S.LOAN_DUE, 0) > 0 AND (ISNULL(S.LOAN_EMI, 0) <= 0 OR ISNULL(S.LOAN_DUE, 0) > 3 * ISNULL(S.LOAN_EMI, 0)) THEN ISNULL(S.LOAN_DUE, 0) ELSE 0 END) AS B3_AMOUNT
      FROM SHG_MEMBER_MCP_INFO MCP WITH (NOLOCK)
     INNER JOIN SN.SHG_MEMBER_LOAN_STATUS_NEW S WITH (NOLOCK) ON S.SHG_MEMBER_LOAN_ACCNO = MCP.SHG_MEMBER_LOAN_ACCNO
     INNER JOIN (SELECT MEMBER_ID, MAX(SHG_ID) AS SHG_ID, MAX(CATAGORY) AS CATEGORY
                   FROM SHG_MEMBER_INFO WITH (NOLOCK)
                  WHERE IS_MEM_ACTIVE = 'Y' AND LEN(LTRIM(RTRIM(MEMBER_ID))) >= 20
                  GROUP BY MEMBER_ID) SM ON SM.MEMBER_ID = MCP.MEMBER_LONG_CODE
     INNER JOIN SHG_INFO SI WITH (NOLOCK) ON SI.TRANS_SHG_ID = SM.SHG_ID AND SI.IS_ACTIVE = 'Y'
     INNER JOIN VO_INFO VI WITH (NOLOCK) ON VI.TRANS_VO_ID = SI.VO_ID AND VI.IS_ACTIVE = 'Y'
     WHERE MCP.LOAN_STATUS = 'OPEN' AND S.IS_CLOSED = 0
       AND MCP.MEMBER_LONG_CODE IS NOT NULL
       AND LTRIM(RTRIM(MCP.MEMBER_LONG_CODE)) <> ''
       AND LEN(MCP.MEMBER_LONG_CODE) >= 20
       AND MCP.ISSUED_DATE IS NOT NULL
       AND MCP.ISSUED_DATE > '2000-01-01'
       AND MCP.LOAN_STATUS IN ('OPEN', 'CLOSED')
       AND (@SnOnly = 0 OR MCP.PROJECT_TYPE IN (SELECT PROJECT_TYPE FROM PROJECT_TYPE_LOAN_MAPPING WITH (NOLOCK)
                                                WHERE LTRIM(RTRIM(LOAN_TYPE)) = 'SN'))
       AND EXISTS (SELECT 1 FROM DISTRICT_MASTER DM WITH (NOLOCK)
                    WHERE DM.DISTRICT_ID = VI.DISTRICT_ID AND DM.FLAG = 'Y')
       AND EXISTS (SELECT 1 FROM MANDAL_MASTER MM WITH (NOLOCK)
                    WHERE MM.DISTRICT_ID = VI.DISTRICT_ID AND MM.MANDAL_ID = VI.MANDAL_ID
                      AND MM.IS_ACTIVE = 'Y' AND MM.IS_MEPMA = 'N')
     GROUP BY VI.DISTRICT_ID, VI.MANDAL_ID
     ORDER BY VI.DISTRICT_ID, VI.MANDAL_ID
    OPTION (RECOMPILE);
END
