-- ROUND 4. SELECT-ONLY, read-only. Run the whole file at once; paste all results back in order.
-- "SN loans" below = the same filter the dashboard uses (Stree Nidhi projects, real issued loans, OPEN/CLOSED).

-- 1. Do the status rows agree with the formula  AMOUNT_PAID = EMI + LOAN_DUE - ADVANCE (never below 0)?
SELECT COUNT(*) AS OPEN_ROWS,
       SUM(CASE WHEN AMOUNT_PAID = (CASE WHEN LOAN_EMI + LOAN_DUE - ADVANCE_COLL > 0 THEN LOAN_EMI + LOAN_DUE - ADVANCE_COLL ELSE 0 END) THEN 1 ELSE 0 END) AS FORMULA_MATCHES
FROM SN.SHG_MEMBER_LOAN_STATUS_NEW WITH (NOLOCK) WHERE IS_CLOSED = 0;

-- 2. How old are the status rows of open loans? (latest due dates first)
SELECT TOP 12 DUE_DATE, COUNT(*) AS OPEN_LOANS
FROM SN.SHG_MEMBER_LOAN_STATUS_NEW WITH (NOLOCK) WHERE IS_CLOSED = 0
GROUP BY DUE_DATE ORDER BY DUE_DATE DESC;

-- 3. Open in the status table but NOT open in the loan table (double counting risk)
SELECT M.LOAN_STATUS, COUNT(*) AS LOANS, SUM(S.LOAN_DUE) AS DUE_SUM
FROM SN.SHG_MEMBER_LOAN_STATUS_NEW S WITH (NOLOCK)
JOIN SHG_MEMBER_MCP_INFO M WITH (NOLOCK) ON M.SHG_MEMBER_LOAN_ACCNO = S.SHG_MEMBER_LOAN_ACCNO
WHERE S.IS_CLOSED = 0
GROUP BY M.LOAN_STATUS;

-- 4. SN open loans with no status row, by issue month (is it only new loans?)
SELECT TOP 14 CONVERT(CHAR(7), M.ISSUED_DATE, 120) AS ISSUE_MONTH, COUNT(*) AS LOANS_WITHOUT_STATUS_ROW
FROM SHG_MEMBER_MCP_INFO M WITH (NOLOCK)
WHERE M.LOAN_STATUS = 'OPEN' AND M.MEMBER_LONG_CODE IS NOT NULL AND LEN(M.MEMBER_LONG_CODE) >= 20 AND M.ISSUED_DATE > '2000-01-01'
  AND M.PROJECT_TYPE IN (SELECT PROJECT_TYPE FROM PROJECT_TYPE_LOAN_MAPPING WITH (NOLOCK) WHERE LTRIM(RTRIM(LOAN_TYPE)) = 'SN')
  AND NOT EXISTS (SELECT 1 FROM SN.SHG_MEMBER_LOAN_STATUS_NEW S WITH (NOLOCK) WHERE S.SHG_MEMBER_LOAN_ACCNO = M.SHG_MEMBER_LOAN_ACCNO)
GROUP BY CONVERT(CHAR(7), M.ISSUED_DATE, 120)
ORDER BY ISSUE_MONTH DESC;

-- 5. Overdue by how many EMIs behind (arrears divided by EMI) - SN open loans
SELECT CASE WHEN S.LOAN_DUE <= 0 THEN 'a. none'
            WHEN S.LOAN_EMI <= 0 THEN 'g. EMI missing'
            WHEN S.LOAN_DUE <= S.LOAN_EMI THEN 'b. up to 1 EMI'
            WHEN S.LOAN_DUE <= 2 * S.LOAN_EMI THEN 'c. 1-2 EMIs'
            WHEN S.LOAN_DUE <= 3 * S.LOAN_EMI THEN 'd. 2-3 EMIs'
            WHEN S.LOAN_DUE <= 6 * S.LOAN_EMI THEN 'e. 3-6 EMIs'
            ELSE 'f. over 6 EMIs' END AS ARREARS_BAND,
       COUNT(*) AS LOANS, SUM(S.LOAN_DUE) AS ARREARS_AMOUNT, SUM(S.OUTSTANDING) AS OUTSTANDING_AMOUNT
FROM SHG_MEMBER_MCP_INFO M WITH (NOLOCK)
JOIN SN.SHG_MEMBER_LOAN_STATUS_NEW S WITH (NOLOCK) ON S.SHG_MEMBER_LOAN_ACCNO = M.SHG_MEMBER_LOAN_ACCNO
WHERE M.LOAN_STATUS = 'OPEN' AND S.IS_CLOSED = 0 AND M.MEMBER_LONG_CODE IS NOT NULL AND LEN(M.MEMBER_LONG_CODE) >= 20 AND M.ISSUED_DATE > '2000-01-01'
  AND M.PROJECT_TYPE IN (SELECT PROJECT_TYPE FROM PROJECT_TYPE_LOAN_MAPPING WITH (NOLOCK) WHERE LTRIM(RTRIM(LOAN_TYPE)) = 'SN')
GROUP BY CASE WHEN S.LOAN_DUE <= 0 THEN 'a. none'
              WHEN S.LOAN_EMI <= 0 THEN 'g. EMI missing'
              WHEN S.LOAN_DUE <= S.LOAN_EMI THEN 'b. up to 1 EMI'
              WHEN S.LOAN_DUE <= 2 * S.LOAN_EMI THEN 'c. 1-2 EMIs'
              WHEN S.LOAN_DUE <= 3 * S.LOAN_EMI THEN 'd. 2-3 EMIs'
              WHEN S.LOAN_DUE <= 6 * S.LOAN_EMI THEN 'e. 3-6 EMIs'
              ELSE 'f. over 6 EMIs' END
ORDER BY ARREARS_BAND;

-- 6. Overdue by district (top 10 by arrears amount) - SN open loans
SELECT TOP 10 M.DISTRICT_ID, COUNT(*) AS OPEN_LOANS,
       SUM(CASE WHEN S.LOAN_DUE > 0 THEN 1 ELSE 0 END) AS LOANS_IN_ARREARS,
       SUM(S.LOAN_DUE) AS ARREARS_AMOUNT, SUM(S.OUTSTANDING) AS OUTSTANDING_AMOUNT
FROM SHG_MEMBER_MCP_INFO M WITH (NOLOCK)
JOIN SN.SHG_MEMBER_LOAN_STATUS_NEW S WITH (NOLOCK) ON S.SHG_MEMBER_LOAN_ACCNO = M.SHG_MEMBER_LOAN_ACCNO
WHERE M.LOAN_STATUS = 'OPEN' AND S.IS_CLOSED = 0 AND M.MEMBER_LONG_CODE IS NOT NULL AND LEN(M.MEMBER_LONG_CODE) >= 20 AND M.ISSUED_DATE > '2000-01-01'
  AND M.PROJECT_TYPE IN (SELECT PROJECT_TYPE FROM PROJECT_TYPE_LOAN_MAPPING WITH (NOLOCK) WHERE LTRIM(RTRIM(LOAN_TYPE)) = 'SN')
GROUP BY M.DISTRICT_ID
ORDER BY ARREARS_AMOUNT DESC;
