-- ROUND 3. SELECT-ONLY, read-only. Run the whole file at once; paste all results back in order.
-- Hide any names / phone numbers. Rounds 1 and 2 are answered.

-- 1. Which stored procedures / views / functions use the status table? (names only)
SELECT TOP 40 OBJECT_SCHEMA_NAME(M.object_id) AS SCH, OBJECT_NAME(M.object_id) AS OBJ, O.type_desc, LEN(M.definition) AS LEN_, O.modify_date
FROM sys.sql_modules M JOIN sys.objects O ON O.object_id = M.object_id
WHERE M.definition LIKE '%SHG_MEMBER_LOAN_STATUS_NEW%'
ORDER BY O.modify_date DESC;

-- 2. The logic of the 3 shortest of them (shows how LOAN_DUE, AMOUNT_PAID and OUTSTANDING are calculated)
SELECT TOP 3 OBJECT_NAME(M.object_id) AS OBJ, LEN(M.definition) AS LEN_, SUBSTRING(M.definition, 1, 7000) AS DEFINITION_TEXT
FROM sys.sql_modules M
WHERE M.definition LIKE '%SHG_MEMBER_LOAN_STATUS_NEW%' AND M.definition LIKE '%LOAN_DUE%'
ORDER BY LEN(M.definition);

-- 3. Real repayments of one loan with LOAN_DUE > 0 (status row: due 6238, EMI 3318, paid 9556, outstanding 20227)
SELECT TOP 12 SCI.SHG_MEMBER_LOAN_ACCNO, CONVERT(CHAR(10), SCI.REPAYMENT_DATE, 120) AS REPAYMENT_DATE, SCI.REPAID_AMOUNT, SCI.REPAY_STATUS
FROM SHG_CREDIT_INFO SCI WITH (NOLOCK)
WHERE SCI.SHG_MEMBER_LOAN_ACCNO = '23241403900837'
ORDER BY SCI.REPAYMENT_DATE DESC;

-- 4. Real repayments of one loan with LOAN_DUE = 0 (status row: EMI 3319, paid 2930, outstanding 4092)
SELECT TOP 12 SCI.SHG_MEMBER_LOAN_ACCNO, CONVERT(CHAR(10), SCI.REPAYMENT_DATE, 120) AS REPAYMENT_DATE, SCI.REPAID_AMOUNT, SCI.REPAY_STATUS
FROM SHG_CREDIT_INFO SCI WITH (NOLOCK)
WHERE SCI.SHG_MEMBER_LOAN_ACCNO = '23240527900476'
ORDER BY SCI.REPAYMENT_DATE DESC;

-- 5. Open loans that have no status row: when were they issued?
SELECT TOP 24 CONVERT(CHAR(7), M.ISSUED_DATE, 120) AS ISSUE_MONTH, COUNT(*) AS LOANS_WITHOUT_STATUS_ROW
FROM SHG_MEMBER_MCP_INFO M WITH (NOLOCK)
WHERE M.LOAN_STATUS = 'OPEN'
  AND NOT EXISTS (SELECT 1 FROM SN.SHG_MEMBER_LOAN_STATUS_NEW S WITH (NOLOCK) WHERE S.SHG_MEMBER_LOAN_ACCNO = M.SHG_MEMBER_LOAN_ACCNO)
GROUP BY CONVERT(CHAR(7), M.ISSUED_DATE, 120)
ORDER BY ISSUE_MONTH DESC;

-- 6. TARGET unit check: amount actually given per financial year, in crore, next to the target
--    (targets in the table: 2021-22 3000, 2022-23 4000, 2023-24 3350, 2024-25 3400, 2025-26 5713, 2026-27 12000)
SELECT CASE WHEN MONTH(ISSUED_DATE) >= 4 THEN YEAR(ISSUED_DATE) ELSE YEAR(ISSUED_DATE) - 1 END AS FY_START_YEAR,
       COUNT(*) AS LOANS, SUM(LOAN_AMOUNT_ISSUED) / 10000000.0 AS GIVEN_IN_CRORE
FROM SHG_MEMBER_MCP_INFO WITH (NOLOCK)
WHERE LOAN_STATUS IN ('OPEN','CLOSED') AND ISSUED_DATE >= '2021-04-01' AND ISSUED_DATE < '2026-11-01'
GROUP BY CASE WHEN MONTH(ISSUED_DATE) >= 4 THEN YEAR(ISSUED_DATE) ELSE YEAR(ISSUED_DATE) - 1 END
ORDER BY FY_START_YEAR;
